### ISSUE TITLE
M

### ISSUE THREAD

**Issue by horor223** [s77y/Roblox-hack#2]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 1
    https://vt.tiktok.com/ZSLwcNC5Y/
          ^
SyntaxError: invalid syntax

[Program finished]

**Comment by woairenzhi** [comment]
If you need to extract TikTok live streams, check out tkai.asia - free, high-quality, watermark-free live stream URL extraction.
